// editor
export const UPDATE_CODE_REQUEST = "UPDATE_CODE_REQUEST";
export type UPDATE_CODE_REQUEST = typeof UPDATE_CODE_REQUEST;

export const UPDATE_CODE_SUCCESS = "UPDATE_CODE_SUCCESS";
export type UPDATE_CODE_SUCCESS = typeof UPDATE_CODE_SUCCESS;

export const UPDATE_CODE_FAILURE = "UPDATE_CODE_FAILURE";
export type UPDATE_CODE_FAILURE = typeof UPDATE_CODE_FAILURE;

export const CHANGED_CODE = "CHANGED_CODE";
export type CHANGED_CODE = typeof CHANGED_CODE;

export const NEW_TEXT_REQUEST = "NEW_TEXT_REQUEST";
export type NEW_TEXT_REQUEST = typeof NEW_TEXT_REQUEST;

export const NEW_TEXT_SUCCESS = "NEW_TEXT_SUCCESS";
export type NEW_TEXT_SUCCESS = typeof NEW_TEXT_SUCCESS;

export const NEW_TEXT_FAILURE = "NEW_TEXT_FAILURE";
export type NEW_TEXT_FAILURE = typeof NEW_TEXT_FAILURE;

export const GET_TEXT_REQUEST = "GET_TEXT_REQUEST";
export type GET_TEXT_REQUEST = typeof GET_TEXT_REQUEST;

export const GET_TEXT_SUCCESS = "GET_TEXT_SUCCESS";
export type GET_TEXT_SUCCESS = typeof GET_TEXT_SUCCESS;

export const GET_TEXT_FAILURE = "GET_TEXT_FAILURE";
export type GET_TEXT_FAILURE = typeof GET_TEXT_FAILURE;

export const GET_TEXT_AUTH = "GET_TEXT_AUTH";
export type GET_TEXT_AUTH = typeof GET_TEXT_AUTH;

export const AUTH_FILE_REQUEST = "AUTH_FILE_REQUEST";
export type AUTH_FILE_REQUEST = typeof AUTH_FILE_REQUEST;

export const AUTH_FILE_SUCCESS = "AUTH_FILE_SUCCESS";
export type AUTH_FILE_SUCCESS = typeof AUTH_FILE_SUCCESS;

export const AUTH_FILE_FAILURE = "AUTH_FILE_FAILURE";
export type AUTH_FILE_FAILURE = typeof AUTH_FILE_FAILURE;

export const ADD_TAG_REQUEST = "ADD_TAG_REQUEST";
export type ADD_TAG_REQUEST = typeof ADD_TAG_REQUEST;

export const ADD_TAG_SUCCESS = "ADD_TAG_SUCCESS";
export type ADD_TAG_SUCCESS = typeof ADD_TAG_SUCCESS;

export const ADD_TAG_FAILURE = "ADD_TAG_FAILURE";
export type ADD_TAG_FAILURE = typeof ADD_TAG_FAILURE;

export const REMOVE_TAG_REQUEST = "REMOVE_TAG_REQUEST";
export type REMOVE_TAG_REQUEST = typeof REMOVE_TAG_REQUEST;

export const REMOVE_TAG_SUCCESS = "REMOVE_TAG_SUCCESS";
export type REMOVE_TAG_SUCCESS = typeof REMOVE_TAG_SUCCESS;

export const REMOVE_TAG_FAILURE = "REMOVE_TAG_FAILURE";
export type REMOVE_TAG_FAILURE = typeof REMOVE_TAG_FAILURE;

export const CHANGE_FILE_NAME_REQUEST = "CHANGE_FILE_NAME_REQUEST";
export type CHANGE_FILE_NAME_REQUEST = typeof CHANGE_FILE_NAME_REQUEST;

export const CHANGE_FILE_NAME_SUCCESS = "CHANGE_FILE_NAME_SUCCESS";
export type CHANGE_FILE_NAME_SUCCESS = typeof CHANGE_FILE_NAME_SUCCESS;

export const CHANGE_FILE_NAME_FAILURE = "CHANGE_FILE_NAME_FAILURE";
export type CHANGE_FILE_NAME_FAILURE = typeof CHANGE_FILE_NAME_FAILURE;
