// header

export const SHARE_LINK = "SHARE_LINK";
export type SHARE_LINK = typeof SHARE_LINK;

export const CLOSE_ALERT = "CLOSE_ALERT";
export type CLOSE_ALERT = typeof CLOSE_ALERT;

// dashboard
// add file to account
// remove file from account
// add collection to account
// remove collection from account

// auth
// create account
// log in
// log out
export const CREATE_ACCOUNT_REQUEST = "CREATE_ACCOUNT_REQUEST";
export type CREATE_ACCOUNT_REQUEST = typeof CREATE_ACCOUNT_REQUEST;

export const CREATE_ACCOUNT_SUCCESS = "CREATE_ACCOUNT_SUCCESS";
export type CREATE_ACCOUNT_SUCCESS = typeof CREATE_ACCOUNT_SUCCESS;

export const CREATE_ACCOUNT_FAILURE = "CREATE_ACCOUNT_FAILURE";
export type CREATE_ACCOUNT_FAILURE = typeof CREATE_ACCOUNT_FAILURE;

export const LOG_IN_REQUEST = "LOG_IN_REQUEST";
export type LOG_IN_REQUEST = typeof LOG_IN_REQUEST;

export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export type LOG_IN_SUCCESS = typeof LOG_IN_SUCCESS;

export const LOG_IN_FAILURE = "LOG_IN_FAILURE";
export type LOG_IN_FAILURE = typeof LOG_IN_FAILURE;

export const LOG_OUT_REQUEST = "LOG_OUT_REQUEST";
export type LOG_OUT_REQUEST = typeof LOG_OUT_REQUEST;

export const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS";
export type LOG_OUT_SUCCESS = typeof LOG_OUT_SUCCESS;

export const LOG_OUT_FAILURE = "LOG_OUT_FAILURE";
export type LOG_OUT_FAILURE = typeof LOG_OUT_FAILURE;

export const LOG_IN_PROMPT = "LOG_IN_PROMPT";
export type LOG_IN_PROMPT = typeof LOG_IN_PROMPT;

export const CLOSE_PROMPT = "CLOSE_PROMPT";
export type CLOSE_PROMPT = typeof CLOSE_PROMPT;

export const UPDATE_TOKEN = "UPDATE_TOKEN";
export type UPDATE_TOKEN = typeof UPDATE_TOKEN;

export const GET_DASHBOARD_REQUEST = "GET_DASHBOARD_REQUEST";
export type GET_DASHBOARD_REQUEST = typeof GET_DASHBOARD_REQUEST;

export const GET_DASHBOARD_SUCCESS = "GET_DASHBOARD_SUCCESS";
export type GET_DASHBOARD_SUCCESS = typeof GET_DASHBOARD_SUCCESS;

export const GET_DASHBOARD_FAILURE = "GET_DASHBOARD_FAILURE";
export type GET_DASHBOARD_FAILURE = typeof GET_DASHBOARD_FAILURE;

// collection
export const NEW_COLLECTION_REQUEST = "NEW_COLLECTION_REQUEST";
export type NEW_COLLECTION_REQUEST = typeof NEW_COLLECTION_REQUEST;

export const NEW_COLLECTION_SUCCESS = "NEW_COLLECTION_SUCCESS";
export type NEW_COLLECTION_SUCCESS = typeof NEW_COLLECTION_SUCCESS;

export const NEW_COLLECTION_FAILURE = "NEW_COLLECTION_FAILURE";
export type NEW_COLLECTION_FAILURE = typeof NEW_COLLECTION_FAILURE;

export const GET_COLLECTION_REQUEST = "GET_COLLECTION_REQUEST";
export type GET_COLLECTION_REQUEST = typeof GET_COLLECTION_REQUEST;

export const GET_COLLECTION_SUCCESS = "GET_COLLECTION_SUCCESS";
export type GET_COLLECTION_SUCCESS = typeof GET_COLLECTION_SUCCESS;

export const GET_COLLECTION_FAILURE = "GET_COLLECTION_FAILURE";
export type GET_COLLECTION_FAILURE = typeof GET_COLLECTION_FAILURE;

export const GET_COLLECTION_AUTH = "GET_COLLECTION_AUTH";
export type GET_COLLECTION_AUTH = typeof GET_COLLECTION_AUTH;

export const AUTH_COLLECTION_REQUEST = "AUTH_COLLECTION_REQUEST";
export type AUTH_COLLECTION_REQUEST = typeof AUTH_COLLECTION_REQUEST;

export const AUTH_COLLECTION_SUCCESS = "AUTH_COLLECTION_SUCCESS";
export type AUTH_COLLECTION_SUCCESS = typeof AUTH_COLLECTION_SUCCESS;

export const AUTH_COLLECTION_FAILURE = "AUTH_COLLECTION_FAILURE";
export type AUTH_COLLECTION_FAILURE = typeof AUTH_COLLECTION_FAILURE;

export const LOCK_COLLECTION_REQUEST = "LOCK_COLLECTION_REQUEST";
export type LOCK_COLLECTION_REQUEST = typeof LOCK_COLLECTION_REQUEST;

export const LOCK_COLLECTION_SUCCESS = "LOCK_COLLECTION_SUCCESS";
export type LOCK_COLLECTION_SUCCESS = typeof LOCK_COLLECTION_SUCCESS;

export const LOCK_COLLECTION_FAILURE = "LOCK_COLLECTION_FAILURE";
export type LOCK_COLLECTION_FAILURE = typeof LOCK_COLLECTION_FAILURE;

export const ADD_FILE_TO_COLLECTION_REQUEST = "ADD_FILE_TO_COLLECTION_REQUEST";
export type ADD_FILE_TO_COLLECTION_REQUEST = typeof ADD_FILE_TO_COLLECTION_REQUEST;

export const ADD_FILE_TO_COLLECTION_SUCCESS = "ADD_FILE_TO_COLLECTION_SUCCESS";
export type ADD_FILE_TO_COLLECTION_SUCCESS = typeof ADD_FILE_TO_COLLECTION_SUCCESS;

export const ADD_FILE_TO_COLLECTION_FAILURE = "ADD_FILE_TO_COLLECTION_FAILURE";
export type ADD_FILE_TO_COLLECTION_FAILURE = typeof ADD_FILE_TO_COLLECTION_FAILURE;

export const REMOVE_FILE_FROM_COLLECTION_REQUEST =
  "REMOVE_FILE_FROM_COLLECTION_REQUEST";
export type REMOVE_FILE_FROM_COLLECTION_REQUEST = typeof REMOVE_FILE_FROM_COLLECTION_REQUEST;

export const REMOVE_FILE_FROM_COLLECTION_SUCCESS =
  "REMOVE_FILE_FROM_COLLECTION_SUCCESS";
export type REMOVE_FILE_FROM_COLLECTION_SUCCESS = typeof REMOVE_FILE_FROM_COLLECTION_SUCCESS;

export const REMOVE_FILE_FROM_COLLECTION_FAILURE =
  "REMOVE_FILE_FROM_COLLECTION_FAILURE";
export type REMOVE_FILE_FROM_COLLECTION_FAILURE = typeof REMOVE_FILE_FROM_COLLECTION_FAILURE;

export const CHANGE_COLLECTION_NAME_REQUEST = "CHANGE_COLLECTION_NAME_REQUEST";
export type CHANGE_COLLECTION_NAME_REQUEST = typeof CHANGE_COLLECTION_NAME_REQUEST;

export const CHANGE_COLLECTION_NAME_SUCCESS = "CHANGE_COLLECTION_NAME_SUCCESS";
export type CHANGE_COLLECTION_NAME_SUCCESS = typeof CHANGE_COLLECTION_NAME_SUCCESS;

export const CHANGE_COLLECTION_NAME_FAILURE = "CHANGE_COLLECTION_NAME_FAILURE";
export type CHANGE_COLLECTION_NAME_FAILURE = typeof CHANGE_COLLECTION_NAME_FAILURE;

export const ADD_USER_TO_COLLECTION_REQUEST = "ADD_USER_TO_COLLECTION_REQUEST";
export type ADD_USER_TO_COLLECTION_REQUEST = typeof ADD_USER_TO_COLLECTION_REQUEST;

export const ADD_USER_TO_COLLECTION_SUCCESS = "ADD_USER_TO_COLLECTION_SUCCESS";
export type ADD_USER_TO_COLLECTION_SUCCESS = typeof ADD_USER_TO_COLLECTION_SUCCESS;

export const ADD_USER_TO_COLLECTION_FAILURE = "ADD_USER_TO_COLLECTION_FAILURE";
export type ADD_USER_TO_COLLECTION_FAILURE = typeof ADD_USER_TO_COLLECTION_FAILURE;

export const REMOVE_USER_FROM_COLLECTION_REQUEST =
  "REMOVE_USER_FROM_COLLECTION_REQUEST";
export type REMOVE_USER_FROM_COLLECTION_REQUEST = typeof REMOVE_USER_FROM_COLLECTION_REQUEST;

export const REMOVE_USER_FROM_COLLECTION_SUCCESS =
  "REMOVE_USER_FROM_COLLECTION_SUCCESS";
export type REMOVE_USER_FROM_COLLECTION_SUCCESS = typeof REMOVE_USER_FROM_COLLECTION_SUCCESS;

export const REMOVE_USER_FROM_COLLECTION_FAILURE =
  "REMOVE_USER_FROM_COLLECTION_FAILURE";
export type REMOVE_USER_FROM_COLLECTION_FAILURE = typeof REMOVE_USER_FROM_COLLECTION_FAILURE;

// editor
export const LOCAL_UPDATE_CODE = "LOCAL_UPDATE_CODE";
export type LOCAL_UPDATE_CODE = typeof LOCAL_UPDATE_CODE;

export const UPDATE_CODE_REQUEST = "UPDATE_CODE_REQUEST";
export type UPDATE_CODE_REQUEST = typeof UPDATE_CODE_REQUEST;

export const UPDATE_CODE_SUCCESS = "UPDATE_CODE_SUCCESS";
export type UPDATE_CODE_SUCCESS = typeof UPDATE_CODE_SUCCESS;

export const UPDATE_CODE_FAILURE = "UPDATE_CODE_FAILURE";
export type UPDATE_CODE_FAILURE = typeof UPDATE_CODE_FAILURE;

export const CHANGED_CODE = "CHANGED_CODE";
export type CHANGED_CODE = typeof CHANGED_CODE;

export const NEW_TEXT_REQUEST = "NEW_TEXT_REQUEST";
export type NEW_TEXT_REQUEST = typeof NEW_TEXT_REQUEST;

export const NEW_TEXT_SUCCESS = "NEW_TEXT_SUCCESS";
export type NEW_TEXT_SUCCESS = typeof NEW_TEXT_SUCCESS;

export const NEW_TEXT_FAILURE = "NEW_TEXT_FAILURE";
export type NEW_TEXT_FAILURE = typeof NEW_TEXT_FAILURE;

export const GET_TEXT_REQUEST = "GET_TEXT_REQUEST";
export type GET_TEXT_REQUEST = typeof GET_TEXT_REQUEST;

export const GET_TEXT_SUCCESS = "GET_TEXT_SUCCESS";
export type GET_TEXT_SUCCESS = typeof GET_TEXT_SUCCESS;

export const GET_TEXT_FAILURE = "GET_TEXT_FAILURE";
export type GET_TEXT_FAILURE = typeof GET_TEXT_FAILURE;

export const GET_TEXT_AUTH = "GET_TEXT_AUTH";
export type GET_TEXT_AUTH = typeof GET_TEXT_AUTH;

export const AUTH_FILE_REQUEST = "AUTH_FILE_REQUEST";
export type AUTH_FILE_REQUEST = typeof AUTH_FILE_REQUEST;

export const AUTH_FILE_SUCCESS = "AUTH_FILE_SUCCESS";
export type AUTH_FILE_SUCCESS = typeof AUTH_FILE_SUCCESS;

export const AUTH_FILE_FAILURE = "AUTH_FILE_FAILURE";
export type AUTH_FILE_FAILURE = typeof AUTH_FILE_FAILURE;

export const ADD_TAG_REQUEST = "ADD_TAG_REQUEST";
export type ADD_TAG_REQUEST = typeof ADD_TAG_REQUEST;

export const ADD_TAG_SUCCESS = "ADD_TAG_SUCCESS";
export type ADD_TAG_SUCCESS = typeof ADD_TAG_SUCCESS;

export const ADD_TAG_FAILURE = "ADD_TAG_FAILURE";
export type ADD_TAG_FAILURE = typeof ADD_TAG_FAILURE;

export const REMOVE_TAG_REQUEST = "REMOVE_TAG_REQUEST";
export type REMOVE_TAG_REQUEST = typeof REMOVE_TAG_REQUEST;

export const REMOVE_TAG_SUCCESS = "REMOVE_TAG_SUCCESS";
export type REMOVE_TAG_SUCCESS = typeof REMOVE_TAG_SUCCESS;

export const REMOVE_TAG_FAILURE = "REMOVE_TAG_FAILURE";
export type REMOVE_TAG_FAILURE = typeof REMOVE_TAG_FAILURE;

export const CHANGE_FILE_NAME_REQUEST = "CHANGE_FILE_NAME_REQUEST";
export type CHANGE_FILE_NAME_REQUEST = typeof CHANGE_FILE_NAME_REQUEST;

export const CHANGE_FILE_NAME_SUCCESS = "CHANGE_FILE_NAME_SUCCESS";
export type CHANGE_FILE_NAME_SUCCESS = typeof CHANGE_FILE_NAME_SUCCESS;

export const CHANGE_FILE_NAME_FAILURE = "CHANGE_FILE_NAME_FAILURE";
export type CHANGE_FILE_NAME_FAILURE = typeof CHANGE_FILE_NAME_FAILURE;

export const LOCK_TEXT_REQUEST = "LOCK_TEXT_REQUEST";
export type LOCK_TEXT_REQUEST = typeof LOCK_TEXT_REQUEST;

export const ADD_USER_TO_FILE_REQUEST = "ADD_USER_TO_FILE_REQUEST";
export type ADD_USER_TO_FILE_REQUEST = typeof ADD_USER_TO_FILE_REQUEST;

export const ADD_USER_TO_FILE_SUCCESS = "ADD_USER_TO_FILE_SUCCESS";
export type ADD_USER_TO_FILE_SUCCESS = typeof ADD_USER_TO_FILE_SUCCESS;

export const ADD_USER_TO_FILE_FAILURE = "ADD_USER_TO_FILE_FAILURE";
export type ADD_USER_TO_FILE_FAILURE = typeof ADD_USER_TO_FILE_FAILURE;

export const REMOVE_USER_FROM_FILE_REQUEST = "REMOVE_USER_FROM_FILE_REQUEST";
export type REMOVE_USER_FROM_FILE_REQUEST = typeof REMOVE_USER_FROM_FILE_REQUEST;

export const REMOVE_USER_FROM_FILE_SUCCESS = "REMOVE_USER_FROM_FILE_SUCCESS";
export type REMOVE_USER_FROM_FILE_SUCCESS = typeof REMOVE_USER_FROM_FILE_SUCCESS;

export const REMOVE_USER_FROM_FILE_FAILURE = "REMOVE_USER_FROM_FILE_FAILURE";
export type REMOVE_USER_FROM_FILE_FAILURE = typeof REMOVE_USER_FROM_FILE_FAILURE;

export const LOCK_TEXT_SUCCESS = "LOCK_TEXT_SUCCESS";
export type LOCK_TEXT_SUCCESS = typeof LOCK_TEXT_SUCCESS;

export const LOCK_TEXT_FAILURE = "LOCK_TEXT_FAILURE";
export type LOCK_TEXT_FAILURE = typeof LOCK_TEXT_FAILURE;
