export const NEW_COLLECTION_REQUEST = "NEW_COLLECTION_REQUEST";
export type NEW_COLLECTION_REQUEST = typeof NEW_COLLECTION_REQUEST;

export const NEW_COLLECTION_SUCCESS = "NEW_COLLECTION_SUCCESS";
export type NEW_COLLECTION_SUCCESS = typeof NEW_COLLECTION_SUCCESS;

export const NEW_COLLECTION_FAILURE = "NEW_COLLECTION_FAILURE";
export type NEW_COLLECTION_FAILURE = typeof NEW_COLLECTION_FAILURE;

export const GET_COLLECTION_REQUEST = "GET_COLLECTION_REQUEST";
export type GET_COLLECTION_REQUEST = typeof GET_COLLECTION_REQUEST;

export const GET_COLLECTION_SUCCESS = "GET_COLLECTION_SUCCESS";
export type GET_COLLECTION_SUCCESS = typeof GET_COLLECTION_SUCCESS;

export const GET_COLLECTION_FAILURE = "GET_COLLECTION_FAILURE";
export type GET_COLLECTION_FAILURE = typeof GET_COLLECTION_FAILURE;

export const GET_COLLECTION_AUTH = "GET_COLLECTION_AUTH";
export type GET_COLLECTION_AUTH = typeof GET_COLLECTION_AUTH;

export const AUTH_COLLECTION_REQUEST = "AUTH_COLLECTION_REQUEST";
export type AUTH_COLLECTION_REQUEST = typeof AUTH_COLLECTION_REQUEST;

export const AUTH_COLLECTION_SUCCESS = "AUTH_COLLECTION_SUCCESS";
export type AUTH_COLLECTION_SUCCESS = typeof AUTH_COLLECTION_SUCCESS;

export const AUTH_COLLECTION_FAILURE = "AUTH_COLLECTION_FAILURE";
export type AUTH_COLLECTION_FAILURE = typeof AUTH_COLLECTION_FAILURE;

export const LOCK_COLLECTION_REQUEST = "LOCK_COLLECTION_REQUEST";
export type LOCK_COLLECTION_REQUEST = typeof LOCK_COLLECTION_REQUEST;

export const LOCK_COLLECTION_SUCCESS = "LOCK_COLLECTION_SUCCESS";
export type LOCK_COLLECTION_SUCCESS = typeof LOCK_COLLECTION_SUCCESS;

export const LOCK_COLLECTION_FAILURE = "LOCK_COLLECTION_FAILURE";
export type LOCK_COLLECTION_FAILURE = typeof LOCK_COLLECTION_FAILURE;

export const ADD_FILE_TO_COLLECTION_REQUEST = "ADD_FILE_TO_COLLECTION_REQUEST";
export type ADD_FILE_TO_COLLECTION_REQUEST = typeof ADD_FILE_TO_COLLECTION_REQUEST;

export const ADD_FILE_TO_COLLECTION_SUCCESS = "ADD_FILE_TO_COLLECTION_SUCCESS";
export type ADD_FILE_TO_COLLECTION_SUCCESS = typeof ADD_FILE_TO_COLLECTION_SUCCESS;

export const ADD_FILE_TO_COLLECTION_FAILURE = "ADD_FILE_TO_COLLECTION_FAILURE";
export type ADD_FILE_TO_COLLECTION_FAILURE = typeof ADD_FILE_TO_COLLECTION_FAILURE;

export const REMOVE_FILE_FROM_COLLECTION_REQUEST =
  "REMOVE_FILE_FROM_COLLECTION_REQUEST";
export type REMOVE_FILE_FROM_COLLECTION_REQUEST = typeof REMOVE_FILE_FROM_COLLECTION_REQUEST;

export const REMOVE_FILE_FROM_COLLECTION_SUCCESS =
  "REMOVE_FILE_FROM_COLLECTION_SUCCESS";
export type REMOVE_FILE_FROM_COLLECTION_SUCCESS = typeof REMOVE_FILE_FROM_COLLECTION_SUCCESS;

export const REMOVE_FILE_FROM_COLLECTION_FAILURE =
  "REMOVE_FILE_FROM_COLLECTION_FAILURE";
export type REMOVE_FILE_FROM_COLLECTION_FAILURE = typeof REMOVE_FILE_FROM_COLLECTION_FAILURE;

export const CHANGE_COLLECTION_NAME_REQUEST = "CHANGE_COLLECTION_NAME_REQUEST";
export type CHANGE_COLLECTION_NAME_REQUEST = typeof CHANGE_COLLECTION_NAME_REQUEST;

export const CHANGE_COLLECTION_NAME_SUCCESS = "CHANGE_COLLECTION_NAME_SUCCESS";
export type CHANGE_COLLECTION_NAME_SUCCESS = typeof CHANGE_COLLECTION_NAME_SUCCESS;

export const CHANGE_COLLECTION_NAME_FAILURE = "CHANGE_COLLECTION_NAME_FAILURE";
export type CHANGE_COLLECTION_NAME_FAILURE = typeof CHANGE_COLLECTION_NAME_FAILURE;

export const ADD_USER_TO_COLLECTION_REQUEST = "ADD_USER_TO_COLLECTION_REQUEST";
export type ADD_USER_TO_COLLECTION_REQUEST = typeof ADD_USER_TO_COLLECTION_REQUEST;

export const ADD_USER_TO_COLLECTION_SUCCESS = "ADD_USER_TO_COLLECTION_SUCCESS";
export type ADD_USER_TO_COLLECTION_SUCCESS = typeof ADD_USER_TO_COLLECTION_SUCCESS;

export const ADD_USER_TO_COLLECTION_FAILURE = "ADD_USER_TO_COLLECTION_FAILURE";
export type ADD_USER_TO_COLLECTION_FAILURE = typeof ADD_USER_TO_COLLECTION_FAILURE;

export const REMOVE_USER_FROM_COLLECTION_REQUEST =
  "REMOVE_USER_FROM_COLLECTION_REQUEST";
export type REMOVE_USER_FROM_COLLECTION_REQUEST = typeof REMOVE_USER_FROM_COLLECTION_REQUEST;

export const REMOVE_USER_FROM_COLLECTION_SUCCESS =
  "REMOVE_USER_FROM_COLLECTION_SUCCESS";
export type REMOVE_USER_FROM_COLLECTION_SUCCESS = typeof REMOVE_USER_FROM_COLLECTION_SUCCESS;

export const REMOVE_USER_FROM_COLLECTION_FAILURE =
  "REMOVE_USER_FROM_COLLECTION_FAILURE";
export type REMOVE_USER_FROM_COLLECTION_FAILURE = typeof REMOVE_USER_FROM_COLLECTION_FAILURE;
